name: Freyja pipeline

# on:
#   schedule:
#     - cron: '0 * * * *'

on:
  push:
    branches:
      - freyja-gh-actions


jobs:
  check_samples_to_run:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    # outputs:
    #   run_rest_jobs: ${{ steps.check_samples_to_run.outputs.run_jobs }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: 'auth'
        name: 'Authenticate with gcloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/12767718289/locations/global/workloadIdentityPools/github/providers/freyja-sra'
          service_account: 'outbreak-ww@andersen-lab-primary.iam.gserviceaccount.com'

      - name: 'Set up gcloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

    
      - name: 'List samples to run'
        run: |
                gcloud storage ls -r gs://modjadji-genomics/NICD-WW/fastqs | grep -o '.*\.fastq\.gz$' | sed 's|.*/||; s|_S.*\.fastq\.gz$||' > samples_in_bucket.txt
                ls outputs | grep -o '.*\.tsv$' | sed 's|.*/||; s|\.demix.tsv$||' > samples_processed.txt
                comm -23 samples_in_bucket.txt samples_processed.txt > samples_to_run.txt


  # run_samples:
  #     needs: [check_samples_to_run]
  #     if: needs.check_samples_to_run.outputs.run_rest_jobs == 'true'
  #     permissions:
  #       contents: write
  #       id-token: write

  #     runs-on: ubuntu-latest

  #     steps:
  #       - name: Checkout main
  #         uses: actions/checkout@v4
  #         with:
  #           token: ${{ secrets.GITHUB_TOKEN }}
            
  #       - name: Setup nextflow
  #         uses: nf-core/setup-nextflow@v1
        
  #       - name: 'Set up Cloud SDK'
  #         uses: 'google-github-actions/setup-gcloud@v2'
  #         with:
  #           version: '>= 363.0.0'
        
  #       - id: 'auth'
  #         name: 'Authenticate with gcloud'
  #         uses: 'google-github-actions/auth@v2'
  #         with:
  #           workload_identity_provider: 'projects/12767718289/locations/global/workloadIdentityPools/github/providers/freyja-sra'
  #           service_account: 'outbreak-ww@andersen-lab-primary.iam.gserviceaccount.com'

  #       - name: 'Get accession list'
  #         id: get_accession_list
  #         run: |
  #               python scripts/get_accession_list.py $BATCH_SIZE

  #       - name: Run pipeline on new samples
  #         run: |
  #                 export NXF_ENABLE_VIRTUAL_THREADS=false
  #                 nextflow run main.nf \
  #                   --accession_list data/accession_list.csv \
  #                   --num_samples $BATCH_SIZE \
  #                   -profile docker \
  #                   -entry aspera &
  #                 BG_PID=$!
  #                 wait $BG_PID

  #       - name: 'Run cryptic variant detection'
  #         run: |
  #               python scripts/cryptic_variants.py...
        
  #       - name: 'Commit and push changes'
  #         run: |
  #               git config --local user.name "$GITHUB_ACTOR"
  #               git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
  #               git remote set-url origin https://github.com/andersen-lab/Freyja-SRA
  #               git add data/all_metadata.csv
  #               git commit -m "Update processed samples"
  #               git push --force

  #       - name: 'Clean workspace'
  #         run: |
  #               rm -rf ${{ github.workspace }}/*