name: Freyja pipeline

# on:
#   schedule:
#     - cron: '0 * * * *'

on:
  push:
    branches:
      - freyja-gh-actions
env:
  BATCH_SIZE: 10

jobs:

  process_samples:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: 'auth'
        name: 'Authenticate with gcloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'andersen-lab-primary'
          workload_identity_provider: 'projects/12767718289/locations/global/workloadIdentityPools/github/providers/nicd-freyja-outputs'

      - name: 'Set up gcloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Set up nextflow
        uses: nf-core/setup-nextflow@v1
    
      - name: 'List samples to run'
        id: list_samples
        run: |
                gcloud storage ls -r gs://modjadji-genomics/NICD-WW/fastqs > fastq_urls.txt
                cat fastq_urls.txt | grep -o '.*\.fastq\.gz$' | sed 's|.*/||; s|_R.*\.fastq\.gz$||' > samples_in_bucket.txt
                ls outputs | grep -o '.*\.tsv$' | sed 's|.*/||; s|\.demix.tsv$||' > samples_processed.txt
                comm -23 samples_in_bucket.txt samples_processed.txt | awk '!seen[$0]++' > samples_to_run.txt
                while read sample; do
                  grep $sample fastq_urls.txt >> samples_to_run_urls.txt
                done < samples_to_run.txt

                cat samples_to_run_urls.txt | head -n $BATCH_SIZE > samples_to_run_batch.txt

                echo "Samples to run:"
                cat samples_to_run_urls.txt | wc -l

      - name: 'Fetch fastqs'
        run: |
                mkdir fastqs
                while read url; do
                  gcloud storage cp $url fastqs/
                done < samples_to_run_batch.txt

      - name: Run pipeline on new samples
        run: |
                nextflow run https://github.com/andersen-lab/Freyja-nf \ 
                  -entry fastq \
                  --fastq_dir fastqs \
                  --output freyja_nf_outputs
                BG_PID=$!
                wait $BG_PID

  #       - name: 'Run cryptic variant detection'
  #         run: |
  #               python scripts/cryptic_variants.py...
        
  #       - name: 'Commit and push changes'
  #         run: |
  #               git config --local user.name "$GITHUB_ACTOR"
  #               git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
  #               git remote set-url origin https://github.com/andersen-lab/Freyja-SRA
  #               git add data/all_metadata.csv
  #               git commit -m "Update processed samples"
  #               git push --force

  #       - name: 'Clean workspace'
  #         run: |
  #               rm -rf ${{ github.workspace }}/*