name: Freyja pipeline
description: |
  https://github.com/andersen-lab/Freyja-nf

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  rerun_demix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: data-dump

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          auto-update-conda: true
          channels: bioconda,conda-forge
          channel-priority: true
          python-version: '3.10'
          activate-environment: test
      
      - name: Install
        shell: bash -l {0}
        run: |
          conda activate test
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda config --add channels bioconda
          conda config --add channels conda-forge  
          conda install --yes freyja pytest pyyaml
  
          
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Re-run demix
        run: |
          cd scripts/
          bash demix_parallel.sh
            