name: Rerun demix

on:
  # schedule:
  #   - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  rerun_demix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: data-dump

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          auto-update-conda: true
          channels: bioconda,conda-forge
          channel-priority: true
          python-version: '3.13'
          activate-environment: test
      
      - name: Install
        shell: bash -l {0}
        run: |
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda config --add channels bioconda
          conda config --add channels conda-forge  
          conda install --yes freyja pytest pyyaml pyarrow=17.0.0
  
          
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          ls -a .
          pip install -r requirements.txt

      - name: Re-run demix
        shell: bash -l {0}
        run: |
          cd scripts/
          bash demix_parallel.sh

      # - name: 'Commit and push changes'
      #   run: |
      #     git config --local user.name "$GITHUB_ACTOR"
      #     git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      #     git remote set-url origin https://github.com/NICD-Wastewater-Genomics/NICD-Freyja-outputs-
      #     git fetch
      #     git branch --set-upstream-to=origin/data-dump
      #     git add outputs figures scripts agg_demixed.tsv
      #     git commit -m "Re-run demix + update freyja metadata"
      #     git push origin data-dump
            