# This workflow will install pytest, and test validity of data in repo.

name: Data integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v2
        with:        
          auto-update-conda: true
          channels: bioconda,conda-forge
          channel-priority: true
          python-version: 3.7
          activate-environment: test
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas pyyaml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda activate test
          pytest

      - name: Clone 
        shell: bash -l {0}
        run: |
            eval `ssh-agent -s`
            ssh-add - <<< '${{ secrets.DASHBOARD_PRIVATE_KEY }}'
            git config --global user.name "joshuailevy"
            git config --global user.email "joshua.levy16@gmail.com"
            git clone git@github.com:NICD-Wastewater-Genomics/Wastewater-Dashboard.git ..
            cp scripts/NICD_daily_smoothed.csv ../Wastewater-Dashboard/Dashboard/data/
            cp scripts/NICD_monthly.csv ../Wastewater-Dashboard/Dashboard/data/
            cp scripts/color_map.json ../Wastewater-Dashboard/Dashboard/data/
            cp scripts/merged_data.tsv ../Wastewater-Dashboard/Dashboard/data/
            cd ../Wastewater-Dashboard

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
          git add --all
    
      - name: Push
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
            git commit -m "automated core data update"
            git push